name: sie-men
channels:
    - conda-forge
dependencies:
    - numpy
    - pandas
    - matplotlib
    - plotly
    - xgboost
    - PIL
    - pickle
    - cartopy
    - datapane
    - geopandas
    - imageio
    - ipyvtklink
    - keplergl
    - laspy
    - localtileserver>=0.4.0
    - osmnx
    - pip
    - pydeck
    - pyntcloud
    - python>=3.9
    - pyvista
    - requests
